version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: smart-task-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - app_network
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  auth:
    build: ./auth_service
    container_name: smart-task-auth
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: auth_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network
    restart: on-failure

  task:
    build: ./task_service
    container_name: smart-task-service
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: task_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network
    restart: on-failure

  frontend:
    image: nginx:alpine
    container_name: smart-task-frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - auth
      - task
    networks:
      - app_network

volumes:
  mysql_data:


networks:
  app_network:
    driver: bridge
