apiVersion: apps/v1
kind: Deployment
metadata:
  name: task
spec:
  replicas: {{ .Values.task.replicas }}
  selector:
    matchLabels:
      app: task
  template:
    metadata:
      labels:
        app: task
    spec:
      containers:
      - name: task
        image: {{ .Values.task.image }}
        ports:
        - containerPort: 5001
        env:
        - name: DB_HOST
          value: {{ .Values.mysql.serviceName | quote }}
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: {{ .Values.mysql.rootPassword | quote }}
        - name: DB_NAME
          value: "task_db"
---
apiVersion: v1
kind: Service
metadata:
  name: task
spec:
  selector:
    app: task
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
